import { StyleSheet } from 'react-native';

export const createAdminStyles = (colorScheme: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colorScheme.backgroundPrimary,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: colorScheme.borderPrimary,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      flex: 1,
    },
    headerBackButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colorScheme.backgroundSecondary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitleGroup: {
      flex: 1,
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: colorScheme.textPrimary,
    },
    headerSubtitle: {
      fontSize: 13,
      color: colorScheme.textMuted,
      marginTop: 2,
    },
    content: {
      flex: 1,
      padding: 20,
      maxWidth: 720,
      width: '100%',
      alignSelf: 'center',
    },
    scrollContent: {
      padding: 20,
      paddingBottom: 60,
      maxWidth: 720,
      width: '100%',
      alignSelf: 'center',
    },

    // ---- List screen ----
    card: {
      backgroundColor: colorScheme.backgroundSecondary,
      borderRadius: 16,
      padding: 20,
      marginBottom: 24,
    },
    cardTitle: {
      fontSize: 13,
      fontWeight: '600',
      color: colorScheme.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginBottom: 14,
    },
    newPuzzleRow: {
      flexDirection: 'row',
      gap: 12,
      alignItems: 'center',
    },
    dateInput: {
      flex: 1,
      backgroundColor: colorScheme.backgroundPrimary,
      borderRadius: 10,
      padding: 14,
      fontSize: 16,
      color: colorScheme.textPrimary,
      borderWidth: 1,
      borderColor: colorScheme.borderPrimary,
    },
    helperText: {
      fontSize: 12,
      color: colorScheme.textMuted,
      marginTop: 10,
    },
    listHeaderRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    sectionTitle: {
      fontSize: 13,
      fontWeight: '600',
      color: colorScheme.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    countBadge: {
      fontSize: 13,
      color: colorScheme.textMuted,
    },
    puzzleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colorScheme.backgroundSecondary,
      borderRadius: 12,
      marginBottom: 8,
      paddingRight: 8,
    },
    puzzleRowMain: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 14,
    },
    puzzleRowIcon: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: colorScheme.backgroundTertiary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    puzzleRowTextGroup: {
      flex: 1,
    },
    puzzleRowText: {
      fontSize: 16,
      fontWeight: '600',
      color: colorScheme.textPrimary,
    },
    puzzleRowSubtext: {
      fontSize: 12,
      color: colorScheme.textMuted,
      marginTop: 2,
    },
    todayPill: {
      backgroundColor: colorScheme.brandPrimary,
      borderRadius: 8,
      paddingHorizontal: 8,
      paddingVertical: 3,
      marginRight: 4,
    },
    todayPillText: {
      fontSize: 11,
      fontWeight: '700',
      color: colorScheme.textPrimary,
    },
    scheduledPill: {
      backgroundColor: colorScheme.backgroundTertiary,
      borderRadius: 8,
      paddingHorizontal: 8,
      paddingVertical: 3,
      marginRight: 4,
    },
    scheduledPillText: {
      fontSize: 11,
      fontWeight: '700',
      color: colorScheme.textSecondary,
    },
    deleteButton: {
      padding: 10,
    },
    emptyState: {
      alignItems: 'center',
      paddingVertical: 40,
      gap: 8,
    },
    emptyText: {
      color: colorScheme.textMuted,
      fontSize: 14,
      textAlign: 'center',
    },

    // ---- Editor form ----
    formSection: {
      marginBottom: 20,
    },
    label: {
      fontSize: 14,
      fontWeight: '600',
      color: colorScheme.textSecondary,
      marginBottom: 6,
    },
    dateBadge: {
      alignSelf: 'flex-start',
      backgroundColor: colorScheme.backgroundSecondary,
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 10,
      marginBottom: 20,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    dateBadgeText: {
      fontSize: 15,
      fontWeight: '600',
      color: colorScheme.textPrimary,
    },
    input: {
      backgroundColor: colorScheme.backgroundSecondary,
      borderRadius: 10,
      padding: 12,
      fontSize: 15,
      color: colorScheme.textPrimary,
      borderWidth: 1,
      borderColor: colorScheme.borderPrimary,
    },
    inputError: {
      borderColor: colorScheme.error,
    },
    categoryColumns: {
      flexDirection: 'row',
      gap: 16,
    },
    categoryColumn: {
      flex: 1,
    },
    categoryColumnTitle: {
      fontSize: 12,
      fontWeight: '700',
      color: colorScheme.brandPrimary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginBottom: 10,
    },
    categoryRow: {
      marginBottom: 10,
    },
    categoryInputLabel: {
      fontSize: 11,
      color: colorScheme.textMuted,
      marginBottom: 4,
    },
    gridScrollHint: {
      fontSize: 12,
      color: colorScheme.textMuted,
      marginBottom: 10,
    },
    gridWrapper: {
      backgroundColor: colorScheme.backgroundSecondary,
      borderRadius: 16,
      padding: 16,
    },
    gridHeaderRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 8,
    },
    gridHeaderSpacer: {
      width: 110,
    },
    gridHeaderCell: {
      width: 120,
      fontSize: 12,
      fontWeight: '700',
      color: colorScheme.brandPrimary,
      textAlign: 'center',
    },
    gridRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 8,
      alignItems: 'center',
    },
    gridRowLabel: {
      width: 110,
      fontSize: 13,
      fontWeight: '600',
      color: colorScheme.textSecondary,
    },
    gridCellInput: {
      width: 120,
    },
    errorBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      backgroundColor: colorScheme.errorBg,
      borderRadius: 10,
      padding: 12,
      marginBottom: 16,
    },
    errorBannerText: {
      color: colorScheme.errorText,
      fontSize: 13,
      flex: 1,
    },
    saveBar: {
      flexDirection: 'row',
      gap: 12,
      marginTop: 8,
      marginBottom: 40,
    },
    fieldCounter: {
      fontSize: 12,
      color: colorScheme.textMuted,
      marginTop: 8,
    },
    fieldCounterComplete: {
      color: colorScheme.success,
    },

    // ---- Confirmation modal ----
    modalOverlay: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.6)',
      padding: 20,
    },
    modalOverlayWeb: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 1000,
    },
    modalCard: {
      backgroundColor: colorScheme.backgroundSecondary,
      borderRadius: 20,
      padding: 24,
      maxWidth: 480,
      width: '100%',
      gap: 4,
      maxHeight: '90%',
    },
    modalIconRow: {
      alignItems: 'center',
      marginBottom: 8,
    },
    modalSuccessIcon: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: colorScheme.successBg,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: colorScheme.textPrimary,
      textAlign: 'center',
    },
    modalSubtitle: {
      fontSize: 14,
      color: colorScheme.textSecondary,
      textAlign: 'center',
      marginTop: 4,
      marginBottom: 16,
    },
    previewGrid: {
      backgroundColor: colorScheme.backgroundPrimary,
      borderRadius: 12,
      padding: 12,
      marginBottom: 16,
    },
    previewHeaderRow: {
      flexDirection: 'row',
    },
    previewCornerCell: {
      width: 70,
    },
    previewColHeaderCell: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 2,
    },
    previewColHeaderText: {
      fontSize: 10,
      fontWeight: '700',
      color: colorScheme.brandPrimary,
      textAlign: 'center',
      textTransform: 'capitalize',
    },
    previewRow: {
      flexDirection: 'row',
      marginTop: 4,
    },
    previewRowHeaderCell: {
      width: 70,
      justifyContent: 'center',
    },
    previewRowHeaderText: {
      fontSize: 10,
      fontWeight: '700',
      color: colorScheme.brandPrimary,
      textTransform: 'capitalize',
    },
    previewCell: {
      flex: 1,
      backgroundColor: colorScheme.backgroundTertiary,
      borderRadius: 8,
      marginHorizontal: 2,
      paddingVertical: 8,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 40,
    },
    previewCellText: {
      fontSize: 11,
      fontWeight: '600',
      color: colorScheme.textPrimary,
      textAlign: 'center',
    },
    modalButtonGroup: {
      gap: 10,
    },
  });
