import { StyleSheet } from 'react-native';
import { ColorScheme, Fonts } from '@/constants/theme';

export const createStyles = (colorScheme: ColorScheme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colorScheme.backgroundPrimary,
  },
  // Home header styles
  homeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colorScheme.borderPrimary,
  },
  homeHeaderLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  homeHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerStreakBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colorScheme.warningBg,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colorScheme.warning,
  },
  headerStreakFlame: {
    marginRight: 4,
  },
  headerStreakText: {
    fontSize: 14,
    fontWeight: '700',
    color: colorScheme.warning,
  },
  headerFriendsButton: {
    padding: 8,
    marginRight: 8,
    position: 'relative',
  },
  headerFriendsBadge: {
    position: 'absolute',
    top: 2,
    right: 2,
    backgroundColor: colorScheme.error,
    borderRadius: 8,
    minWidth: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  headerFriendsBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: colorScheme.textPrimary,
  },
  headerProfileButton: {
    padding: 4,
  },
  headerProfileIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colorScheme.brandSecondary,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  headerProfileInitial: {
    fontSize: 16,
    fontWeight: '600',
    color: colorScheme.textPrimary,
  },
  headerProfileImage: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  headerSignInButton: {
    backgroundColor: colorScheme.gold,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  headerSignInText: {
    fontSize: 14,
    fontWeight: '700',
    color: colorScheme.warmBlack,
  },
  // Main menu styles
  mainMenuScroll: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  mainMenu: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    paddingVertical: 24,
  },
  menuLogoFrame: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    overflow: 'hidden',
    marginBottom: -10,
  },
  menuLogo: {
    width: 190,
    height: 190,
    marginBottom: 0,
  },
  menuTitle: {
    fontSize: 48,
    fontWeight: 'bold',
    color: colorScheme.textPrimary,
    marginBottom: 8,
  },
  menuSubtitle: {
    fontSize: 18,
    color: colorScheme.textTertiary,
    marginBottom: 16,
  },
  menuButtons: {
    width: '100%',
    maxWidth: 400,
    gap: 16,
  },
  playButton: {
    backgroundColor: colorScheme.gold,
    padding: 24,
    borderRadius: 16,
    alignItems: 'center',
  },
  playButtonLabelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  completedButton: {
    backgroundColor: colorScheme.successBg,
    borderWidth: 2,
    borderColor: colorScheme.success,
  },
  playButtonLabel: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colorScheme.warmBlack,
    marginBottom: 4,
  },
  playButtonDesc: {
    fontSize: 14,
    color: colorScheme.warmGray,
  },
  playButtonError: {
    fontSize: 13,
    color: colorScheme.errorText,
    textAlign: 'center',
  },
  // Completed container styles (condensed leaderboard)
  completedContainer: {
    backgroundColor: colorScheme.backgroundSecondary,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: colorScheme.borderPrimary,
  },
  completedHeader: {
    position: 'relative',
    alignItems: 'center',
    marginBottom: 12,
  },
  completedHeaderContent: {
    alignItems: 'center',
    gap: 6,
  },
  completedHeaderTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  refreshButton: {
    position: 'absolute',
    top: 0,
    right: 0,
    padding: 4,
  },
  refreshingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colorScheme.overlayMedium,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    zIndex: 1,
  },
  leaderboardLoadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    gap: 10,
  },
  leaderboardLoadingText: {
    fontSize: 14,
    color: colorScheme.textTertiary,
  },
  completedTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colorScheme.textPrimary,
  },
  completedRankText: {
    fontSize: 13,
    fontWeight: '600',
    color: colorScheme.gold,
  },
  tapForDetailsHint: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    gap: 4,
  },
  tapForDetailsText: {
    fontSize: 12,
    color: colorScheme.textMuted,
  },
  leaderboardSectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colorScheme.textTertiary,
    textTransform: 'uppercase',
  },
  leaderboardEmptyText: {
    fontSize: 14,
    color: colorScheme.textMuted,
    textAlign: 'center',
    paddingVertical: 12,
  },
  leaderboardCompact: {
    gap: 4,
  },
  leaderboardCompactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderRadius: 8,
  },
  leaderboardCompactRowCurrentUser: {
    backgroundColor: colorScheme.overlayLight,
  },
  leaderboardCompactRank: {
    width: 32,
    alignItems: 'center',
  },
  leaderboardCompactRankText: {
    fontSize: 14,
    fontWeight: '600',
    color: colorScheme.textTertiary,
  },
  leaderboardCompactName: {
    flex: 1,
    fontSize: 14,
    color: colorScheme.textSecondary,
    marginLeft: 8,
  },
  leaderboardCompactNameCurrentUser: {
    color: colorScheme.brandPrimary,
    fontWeight: '600',
  },
  leaderboardCompactCorrect: {
    fontSize: 12,
    color: colorScheme.textTertiary,
    marginRight: 8,
  },
  leaderboardCompactScore: {
    fontSize: 14,
    fontWeight: '700',
    color: colorScheme.success,
  },
  leaderboardCompactScoreCurrentUser: {
    color: colorScheme.brandPrimary,
  },
  leaderboardDivider: {
    alignItems: 'center',
    paddingVertical: 4,
  },
  leaderboardDividerText: {
    fontSize: 12,
    color: colorScheme.textMuted,
  },
  viewFullLeaderboardButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: colorScheme.borderPrimary,
  },
  viewFullLeaderboardText: {
    fontSize: 13,
    color: colorScheme.brandPrimary,
    marginRight: 4,
  },
  viewAnswersMainButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colorScheme.borderPrimary,
    backgroundColor: colorScheme.backgroundSecondary,
    paddingVertical: 14,
    gap: 8,
  },
  viewAnswersMainText: {
    fontSize: 15,
    fontWeight: '600',
    color: colorScheme.brandPrimary,
  },
  // Answers toggle and container
  answersToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colorScheme.backgroundSecondary,
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
  },
  answersToggleLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  answersToggleText: {
    fontSize: 14,
    fontWeight: '600',
    color: colorScheme.brandPrimary,
  },
  answersContainer: {
    alignItems: 'center',
    marginBottom: 12,
    paddingTop: 8,
  },
  // Answers Modal styles
  answersModalContainer: {
    flex: 1,
    backgroundColor: colorScheme.backgroundPrimary,
  },
  answersModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colorScheme.borderPrimary,
  },
  answersModalBackButton: {
    padding: 8,
  },
  answersModalCloseButton: {
    padding: 8,
  },
  answersModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colorScheme.textPrimary,
  },
  answersModalContent: {
    alignItems: 'center',
    padding: 20,
  },
  answersEmptyState: {
    alignItems: 'center',
    gap: 12,
  },
  answersEmptyText: {
    fontSize: 16,
    color: colorScheme.textTertiary,
    textAlign: 'center',
  },
  answersEmptyButton: {
    borderWidth: 1,
    borderColor: colorScheme.borderAccent,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  answersEmptyButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: colorScheme.brandPrimary,
  },
  tutorialScreenContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 28,
  },
  // Full-screen leaderboard styles
  leaderboardScreenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colorScheme.borderPrimary,
  },
  leaderboardScreenBackButton: {
    padding: 8,
  },
  leaderboardScreenTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  leaderboardScreenTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colorScheme.textPrimary,
  },
  leaderboardScreenRefreshButton: {
    padding: 8,
    width: 40,
    alignItems: 'center',
  },
  leaderboardTabBar: {
    flexDirection: 'row',
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 8,
    backgroundColor: colorScheme.backgroundTertiary,
    borderRadius: 14,
    padding: 3,
  },
  leaderboardTab: {
    flex: 1,
    paddingVertical: 6,
    alignItems: 'center',
    borderRadius: 11,
  },
  leaderboardTabActive: {
    backgroundColor: colorScheme.brandPrimary,
  },
  leaderboardTabText: {
    fontSize: 12,
    fontWeight: '500',
    color: colorScheme.textTertiary,
  },
  leaderboardTabTextActive: {
    color: colorScheme.textPrimary,
    fontWeight: '600',
  },
  leaderboardScreenContent: {
    flex: 1,
  },
  leaderboardScreenContentContainer: {
    padding: 16,
  },
  leaderboardScreenLoadingOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  leaderboardScreenLoadingText: {
    fontSize: 16,
    color: colorScheme.info,
    fontFamily: Fonts.rounded,
  },
  leaderboardScreenRefreshingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colorScheme.overlayMedium,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  userRankBanner: {
    backgroundColor: colorScheme.successBg,
    borderRadius: 12,
    padding: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colorScheme.successDark,
  },
  userRankBannerContent: {
    flex: 1,
  },
  userRankBannerText: {
    fontSize: 12,
    color: colorScheme.successText,
  },
  userRankBannerValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colorScheme.gold,
    marginTop: 2,
  },
  userRankShareButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colorScheme.success,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 12,
  },
  leaderboardFullList: {
    gap: 8,
  },
  leaderboardFullRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colorScheme.backgroundSecondary,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  leaderboardFullRowCurrentUser: {
    backgroundColor: colorScheme.overlayLight,
    borderWidth: 1,
    borderColor: colorScheme.borderAccent,
  },
  leaderboardFullRank: {
    width: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  leaderboardFullRankText: {
    fontSize: 16,
    fontWeight: '600',
    color: colorScheme.textTertiary,
  },
  leaderboardFullInfo: {
    flex: 1,
    marginLeft: 8,
  },
  leaderboardFullName: {
    fontSize: 16,
    color: colorScheme.textPrimary,
    fontWeight: '500',
  },
  leaderboardFullNameCurrentUser: {
    color: colorScheme.brandPrimary,
  },
  leaderboardFullMeta: {
    fontSize: 13,
    color: colorScheme.textTertiary,
    marginTop: 2,
  },
  leaderboardFullScore: {
    fontSize: 20,
    fontWeight: '700',
    color: colorScheme.success,
    marginLeft: 12,
  },
  leaderboardFullScoreCurrentUser: {
    color: colorScheme.brandPrimary,
  },
  leaderboardAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colorScheme.brandSecondary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  leaderboardAvatarImage: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  leaderboardAvatarText: {
    fontSize: 14,
    fontWeight: '600',
    color: colorScheme.textPrimary,
  },
  leaderboardScreenActions: {
    marginTop: 24,
    gap: 12,
  },
  leaderboardScreenActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: colorScheme.borderAccent,
    borderRadius: 12,
    paddingVertical: 14,
    gap: 8,
  },
  leaderboardScreenActionText: {
    fontSize: 16,
    fontWeight: '600',
    color: colorScheme.brandPrimary,
  },
  leaderboardScreenShareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: colorScheme.success,
    borderRadius: 12,
    paddingVertical: 14,
    marginBottom: 16,
    gap: 8,
  },
  leaderboardScreenShareText: {
    fontSize: 16,
    fontWeight: '600',
    color: colorScheme.success,
  },
  // Share score button
  shareScoreButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: colorScheme.success,
    borderRadius: 8,
    paddingVertical: 12,
    gap: 8,
  },
  shareScoreButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: colorScheme.success,
  },
  // Leaderboard card styles
  leaderboardCard: {
    backgroundColor: colorScheme.backgroundSecondary,
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: colorScheme.borderPrimary,
  },
  leaderboardCardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  leaderboardCardIcon: {
    marginRight: 0,
  },
  leaderboardCardTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colorScheme.textPrimary,
  },
  leaderboardCardDesc: {
    fontSize: 13,
    color: colorScheme.textTertiary,
    marginTop: 2,
  },
  // Leaderboard preview styles (on card)
  leaderboardPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  leaderboardPreviewItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  leaderboardPreviewScore: {
    fontSize: 12,
    color: colorScheme.textTertiary,
    fontWeight: '600',
  },
  leaderboardPreviewScoreCurrentUser: {
    color: colorScheme.brandPrimary,
  },
  // How to play button
  howToPlayButton: {
    marginTop: 16,
    width: '100%',
    maxWidth: 400,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colorScheme.borderPrimary,
    backgroundColor: colorScheme.backgroundSecondary,
    paddingVertical: 14,
    gap: 8,
  },
  howToPlayText: {
    fontSize: 15,
    fontWeight: '600',
    color: colorScheme.brandPrimary,
  },
  // Sign in banner styles
  signInBanner: {
    backgroundColor: colorScheme.backgroundSecondary,
    borderBottomWidth: 1,
    borderBottomColor: colorScheme.borderPrimary,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  signInBannerContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  signInBannerText: {
    flex: 1,
  },
  signInBannerTitle: {
    fontSize: 13,
    color: colorScheme.textSecondary,
    lineHeight: 18,
  },
  signInBannerButton: {
    backgroundColor: colorScheme.gold,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
  },
  signInBannerButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: colorScheme.warmBlack,
  },
  signInBannerDismiss: {
    padding: 8,
    marginLeft: 4,
  },
  signInBannerDismissText: {
    fontSize: 20,
    color: colorScheme.textMuted,
    fontWeight: '300',
  },
  // Account section (for signed in users)
  accountSection: {
    marginTop: 24,
    alignItems: 'center',
    gap: 4,
  },
  accountSectionEmail: {
    fontSize: 13,
    color: colorScheme.textMuted,
  },
  accountSectionSignOut: {
    fontSize: 14,
    color: colorScheme.textTertiary,
    marginTop: 4,
  },
  scoreSummary: {
    alignItems: 'center',
  },
  scoreSummaryLoading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
  },
  playButtonLoading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
  },
  playButtonLoadingText: {
    fontSize: 18,
    color: colorScheme.textPrimary,
    fontWeight: '500',
  },
  scoreSummaryText: {
    fontSize: 16,
    color: colorScheme.success,
    fontWeight: '600',
    marginBottom: 4,
  },
  percentileText: {
    fontSize: 14,
    color: colorScheme.warning,
    fontWeight: '500',
    marginBottom: 4,
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginBottom: 20,
  },
  dateText: {
    fontSize: 16,
    color: colorScheme.textMuted,
  },
  completedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colorScheme.successBg,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  completedBadgeText: {
    fontSize: 13,
    color: colorScheme.success,
    fontWeight: '600',
  },
  footerLinks: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 24,
    marginBottom: 20,
    gap: 12,
    flexWrap: 'wrap',
  },
  footerLinkText: {
    fontSize: 13,
    color: colorScheme.textDisabled,
  },
  footerLinkDivider: {
    fontSize: 13,
    color: colorScheme.googleButtonText,
  },
  streakContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 24,
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: colorScheme.warningBg,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colorScheme.warning,
  },
  streakFlame: {
    fontSize: 18,
    marginRight: 6,
  },
  streakText: {
    fontSize: 16,
    fontWeight: '600',
    color: colorScheme.warning,
  },
  // Sign in styles
  signInButton: {
    marginTop: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  signInText: {
    fontSize: 14,
    color: colorScheme.brandPrimary,
  },
  accountContainer: {
    marginTop: 16,
    alignItems: 'center',
    gap: 4,
  },
  accountDisplayName: {
    fontSize: 16,
    fontWeight: '600',
    color: colorScheme.brandPrimary,
    marginBottom: 2,
  },
  accountEmail: {
    fontSize: 13,
    color: colorScheme.textMuted,
  },
  signOutText: {
    fontSize: 14,
    color: colorScheme.textTertiary,
    marginTop: 4,
  },
  // Display name modal styles
  displayNameModal: {
    backgroundColor: colorScheme.backgroundSecondary,
    borderRadius: 16,
    padding: 24,
    maxWidth: 360,
    width: '100%',
    alignItems: 'center',
  },
  displayNameTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colorScheme.textPrimary,
    marginBottom: 8,
  },
  displayNameSubtitle: {
    fontSize: 14,
    color: colorScheme.textTertiary,
    textAlign: 'center',
    marginBottom: 20,
  },
  displayNameInput: {
    backgroundColor: colorScheme.backgroundTertiary,
    borderRadius: 8,
    padding: 14,
    fontSize: 16,
    color: colorScheme.textPrimary,
    width: '100%',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colorScheme.borderSecondary,
  },
  displayNameErrorText: {
    color: colorScheme.errorText,
    fontSize: 13,
    marginBottom: 12,
    textAlign: 'center',
  },
  displayNameSaveButton: {
    backgroundColor: colorScheme.success,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 8,
    width: '100%',
    alignItems: 'center',
  },
  displayNameSaveButtonDisabled: {
    backgroundColor: colorScheme.successDark,
  },
  displayNameSaveText: {
    fontSize: 16,
    fontWeight: '600',
    color: colorScheme.textPrimary,
  },
  displayNameCancelButton: {
    marginTop: 12,
    paddingVertical: 8,
  },
  displayNameCancelText: {
    fontSize: 15,
    color: colorScheme.textTertiary,
  },
  signInModal: {
    backgroundColor: colorScheme.backgroundSecondary,
    borderRadius: 16,
    padding: 24,
    maxWidth: 360,
    width: '100%',
    alignItems: 'center',
  },
  signInModalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colorScheme.textPrimary,
    marginBottom: 8,
  },
  signInModalSubtitle: {
    fontSize: 14,
    color: colorScheme.textTertiary,
    textAlign: 'center',
    marginBottom: 24,
  },
  googleButton: {
    backgroundColor: colorScheme.googleButton,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 8,
    width: '100%',
    alignItems: 'center',
    marginBottom: 16,
  },
  googleButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  googleButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: colorScheme.googleButtonText,
  },
  appleButton: {
    width: '100%',
    height: 48,
    marginBottom: 16,
    backgroundColor: colorScheme.appleButton,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  appleButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  appleButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: colorScheme.textPrimary,
  },
  signInCancelButton: {
    paddingVertical: 12,
  },
  signInCancelText: {
    fontSize: 16,
    color: colorScheme.textTertiary,
  },
  // Profile menu modal styles
  profileMenuModal: {
    backgroundColor: colorScheme.backgroundSecondary,
    borderRadius: 16,
    padding: 16,
    maxWidth: 320,
    width: '100%',
  },
  profileMenuHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    gap: 12,
  },
  profileMenuAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colorScheme.brandSecondary,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  profileMenuAvatarText: {
    fontSize: 20,
    fontWeight: '600',
    color: colorScheme.textPrimary,
  },
  profileMenuAvatarImage: {
    width: 48,
    height: 48,
    borderRadius: 24,
  },
  profileMenuInfo: {
    flex: 1,
  },
  profileMenuName: {
    fontSize: 16,
    fontWeight: '600',
    color: colorScheme.textPrimary,
  },
  profileMenuEmail: {
    fontSize: 13,
    color: colorScheme.textTertiary,
    marginTop: 2,
  },
  profileMenuDivider: {
    height: 1,
    backgroundColor: colorScheme.backgroundTertiary,
    marginVertical: 8,
  },
  profileMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 8,
    gap: 12,
  },
  profileMenuItemIcon: {
    marginRight: 0,
  },
  profileMenuItemText: {
    fontSize: 15,
    color: colorScheme.textPrimary,
    flex: 1,
  },
  profileMenuItemTextDanger: {
    fontSize: 15,
    color: colorScheme.error,
  },
  profileMenuBadge: {
    backgroundColor: colorScheme.error,
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 6,
  },
  profileMenuBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: colorScheme.textPrimary,
  },
  profileMenuSection: {
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  profileMenuSectionTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: colorScheme.textTertiary,
    marginBottom: 10,
    letterSpacing: 0.5,
  },
  themeOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  themeOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 14,
    backgroundColor: colorScheme.backgroundTertiary,
    borderWidth: 1,
    borderColor: colorScheme.borderPrimary,
  },
  themeOptionActive: {
    backgroundColor: colorScheme.brandSecondary,
    borderColor: colorScheme.borderAccent,
  },
  themeSwatch: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 6,
  },
  themeOptionText: {
    fontSize: 13,
    color: colorScheme.textSecondary,
  },
  themeOptionTextActive: {
    color: colorScheme.textPrimary,
    fontWeight: '600',
  },
  // Toggle switch styles
  toggle: {
    width: 50,
    height: 28,
    borderRadius: 14,
    backgroundColor: colorScheme.backgroundTertiary,
    padding: 2,
    justifyContent: 'center',
  },
  toggleOn: {
    backgroundColor: colorScheme.success,
  },
  toggleThumb: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colorScheme.googleButton,
    shadowColor: colorScheme.appleButton,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
  },
  toggleThumbOn: {
    transform: [{ translateX: 22 }],
  },
  // Menu links row
  menuLinksRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
    gap: 12,
  },
  menuLinkButton: {
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  menuLinkText: {
    fontSize: 16,
    color: colorScheme.textTertiary,
    textDecorationLine: 'underline',
  },
  menuLinkDivider: {
    fontSize: 16,
    color: colorScheme.textDisabled,
  },
  // Leaderboard modal styles
  leaderboardModal: {
    backgroundColor: colorScheme.backgroundSecondary,
    borderRadius: 16,
    padding: 24,
    maxWidth: 400,
    maxHeight: '80%',
    width: '100%',
  },
  leaderboardTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  leaderboardTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colorScheme.textPrimary,
  },
  leaderboardEmpty: {
    fontSize: 16,
    color: colorScheme.textTertiary,
    textAlign: 'center',
    marginVertical: 40,
  },
  leaderboardList: {
    // Removed maxHeight since it's now inside a ScrollView
  },
  leaderboardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: colorScheme.borderPrimary,
  },
  leaderboardRowCurrentUser: {
    backgroundColor: colorScheme.overlayLight,
    borderRadius: 8,
  },
  leaderboardRowSeparated: {
    marginTop: 16,
    borderTopWidth: 1,
    borderTopColor: colorScheme.borderPrimary,
    borderStyle: 'dashed',
  },
  leaderboardRank: {
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  leaderboardRankText: {
    fontSize: 18,
    fontWeight: '600',
    color: colorScheme.textTertiary,
    textAlign: 'center',
  },
  leaderboardInfo: {
    flex: 1,
    marginLeft: 8,
  },
  leaderboardName: {
    fontSize: 16,
    color: colorScheme.textPrimary,
    fontWeight: '500',
  },
  leaderboardNameCurrentUser: {
    color: colorScheme.brandPrimary,
  },
  leaderboardTime: {
    fontSize: 13,
    color: colorScheme.textTertiary,
    marginTop: 2,
  },
  leaderboardScore: {
    fontSize: 18,
    fontWeight: '700',
    color: colorScheme.success,
    marginLeft: 12,
  },
  leaderboardScoreCurrentUser: {
    color: colorScheme.brandPrimary,
  },
  leaderboardCloseButton: {
    marginTop: 16,
    paddingVertical: 14,
    backgroundColor: colorScheme.backgroundTertiary,
    borderRadius: 8,
    alignItems: 'center',
  },
  leaderboardCloseText: {
    fontSize: 16,
    fontWeight: '600',
    color: colorScheme.textPrimary,
  },
  // Enhanced leaderboard modal styles
  leaderboardScrollView: {
    maxHeight: '100%',
  },
  leaderboardUserScore: {
    backgroundColor: colorScheme.successBg,
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colorScheme.successDark,
  },
  leaderboardUserScoreHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  leaderboardUserScoreTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colorScheme.success,
  },
  leaderboardUserRankBadge: {
    backgroundColor: colorScheme.successDark,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  leaderboardUserRankText: {
    fontSize: 14,
    fontWeight: '700',
    color: colorScheme.success,
  },
  leaderboardUserScoreRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  leaderboardUserScoreItem: {
    alignItems: 'center',
  },
  leaderboardUserScoreValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colorScheme.textPrimary,
  },
  leaderboardUserScoreLabel: {
    fontSize: 11,
    color: colorScheme.textTertiary,
    marginTop: 2,
    textTransform: 'uppercase',
  },
  leaderboardUserPercentile: {
    fontSize: 14,
    color: colorScheme.warning,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: 12,
  },
  leaderboardShareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: colorScheme.success,
    borderRadius: 8,
    paddingVertical: 10,
    marginTop: 16,
  },
  leaderboardShareButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: colorScheme.success,
  },
  leaderboardViewAnswersButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: colorScheme.borderAccent,
    borderRadius: 8,
    paddingVertical: 12,
    marginTop: 20,
  },
  leaderboardViewAnswersText: {
    fontSize: 14,
    fontWeight: '600',
    color: colorScheme.brandPrimary,
  },
  // Tutorial modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: colorScheme.overlayDark,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalOverlayWeb: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 1000,
  },
  tutorialModal: {
    backgroundColor: colorScheme.backgroundSecondary,
    borderRadius: 16,
    padding: 24,
    maxWidth: 400,
    maxHeight: '80%',
    width: '100%',
  },
  tutorialTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: colorScheme.textPrimary,
    textAlign: 'center',
    marginBottom: 24,
  },
  tutorialHeading: {
    fontSize: 18,
    fontWeight: '600',
    color: colorScheme.success,
    marginTop: 16,
    marginBottom: 8,
  },
  tutorialText: {
    fontSize: 15,
    color: colorScheme.textSecondary,
    lineHeight: 22,
  },
  tutorialCloseButton: {
    backgroundColor: colorScheme.gold,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 32,
    alignItems: 'center',
    marginTop: 20,
    borderTopWidth: 1,
    borderTopColor: colorScheme.borderPrimary,
  },
  tutorialCloseText: {
    fontSize: 18,
    fontWeight: '700',
    color: colorScheme.warmBlack,
  },
  // Header styles
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    paddingHorizontal: 16,
    backgroundColor: colorScheme.backgroundSecondary,
    borderBottomWidth: 1,
    borderBottomColor: colorScheme.borderPrimary,
    minHeight: 44,
  },
  headerBackButton: {
    padding: 8,
    width: 44,
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
  },
  headerRight: {
    width: 44,
  },
  headerHelpButton: {
    padding: 8,
    width: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  helpCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colorScheme.textTertiary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerHelpIcon: {
    color: colorScheme.textTertiary,
    fontSize: 14,
    fontWeight: '700',
  },
  timerText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colorScheme.textPrimary,
    fontVariant: ['tabular-nums'],
  },
  headerBackIcon: {
    color: colorScheme.textPrimary,
    fontSize: 28,
  },
  livesContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  livesLabel: {
    color: colorScheme.textTertiary,
    fontSize: 13,
    fontWeight: '600',
    marginRight: 4,
  },
  heart: {
    width: 16,
    height: 16,
    borderRadius: 8,
  },
  heartFilled: {
    backgroundColor: colorScheme.error,
    shadowColor: colorScheme.error,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
  },
  heartEmpty: {
    backgroundColor: colorScheme.backgroundTertiary,
    borderWidth: 1,
    borderColor: colorScheme.borderSecondary,
  },
  instructions: {
    fontSize: 14,
    color: colorScheme.textPrimary,
    textAlign: 'center',
    marginBottom: 8,
    marginTop: 8,
  },
  // Result header with back arrow
  resultHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  // Result scroll content
  resultScrollContent: {
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  // Game over styles
  gameOverText: {
    fontSize: 36,
    fontWeight: 'bold',
    color: colorScheme.errorLight,
    marginBottom: 24,
  },
  percentileCardGameOver: {
    backgroundColor: colorScheme.errorBg,
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 32,
    alignItems: 'center',
    marginBottom: 32,
  },
  percentileValueGameOver: {
    fontSize: 28,
    fontWeight: 'bold',
    color: colorScheme.errorLight,
  },
  percentileLabelGameOver: {
    fontSize: 14,
    color: colorScheme.errorText,
    marginTop: 4,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 12,
  },
  shareButton: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: colorScheme.errorLight,
    paddingHorizontal: 28,
    paddingVertical: 12,
    borderRadius: 25,
  },
  shareButtonText: {
    color: colorScheme.errorLight,
    fontWeight: '600',
    fontSize: 18,
  },
  tryAgainButton: {
    backgroundColor: colorScheme.errorLight,
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderRadius: 25,
  },
  tryAgainText: {
    color: colorScheme.backgroundPrimary,
    fontWeight: '600',
    fontSize: 18,
  },
  // Win overlay styles
  winOverlayTitle: {
    fontSize: 36,
    fontWeight: 'bold',
    color: colorScheme.success,
    marginBottom: 32,
  },
  scoreCard: {
    backgroundColor: colorScheme.successBg,
    borderRadius: 16,
    padding: 24,
    width: '100%',
    maxWidth: 320,
    marginBottom: 24,
  },
  scoreRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  scoreItem: {
    alignItems: 'center',
    minWidth: 80,
  },
  scoreValue: {
    fontSize: 32,
    fontWeight: 'bold',
    color: colorScheme.textPrimary,
  },
  scoreLabel: {
    fontSize: 12,
    color: colorScheme.textTertiary,
    marginTop: 4,
    textTransform: 'uppercase',
  },
  noScoreText: {
    fontSize: 16,
    color: colorScheme.textPrimary,
    textAlign: 'center',
  },
  noScoreSubtext: {
    fontSize: 12,
    color: colorScheme.textTertiary,
    textAlign: 'center',
    marginTop: 4,
  },
  calculatingText: {
    fontSize: 16,
    color: colorScheme.textTertiary,
    marginBottom: 16,
  },
  // Loading result screen styles
  loadingResultContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  loadingResultTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  loadingResultText: {
    fontSize: 16,
    color: colorScheme.textTertiary,
    marginTop: 16,
  },
  percentileCard: {
    backgroundColor: colorScheme.brandSecondary,
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 32,
    alignItems: 'center',
    marginBottom: 32,
  },
  percentileValue: {
    fontSize: 28,
    fontWeight: 'bold',
    color: colorScheme.success,
  },
  percentileLabel: {
    fontSize: 14,
    color: colorScheme.successText,
    marginTop: 4,
  },
  // Rank card styles (win screen)
  rankCardWin: {
    backgroundColor: colorScheme.brandSecondary,
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 32,
    alignItems: 'center',
    marginBottom: 32,
  },
  rankValueWin: {
    fontSize: 36,
    fontWeight: 'bold',
    color: colorScheme.gold,
  },
  rankLabelWin: {
    fontSize: 14,
    color: colorScheme.successText,
    marginTop: 4,
  },
  // Rank card styles (game over screen)
  rankCard: {
    backgroundColor: colorScheme.errorBg,
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 32,
    alignItems: 'center',
    marginBottom: 32,
  },
  rankValue: {
    fontSize: 36,
    fontWeight: 'bold',
    color: colorScheme.gold,
  },
  rankLabel: {
    fontSize: 14,
    color: colorScheme.errorText,
    marginTop: 4,
  },
  shareButtonWin: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: colorScheme.success,
    paddingHorizontal: 28,
    paddingVertical: 12,
    borderRadius: 25,
  },
  shareButtonWinText: {
    color: colorScheme.success,
    fontWeight: '600',
    fontSize: 18,
  },
  menuButton: {
    backgroundColor: colorScheme.success,
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderRadius: 25,
  },
  menuButtonText: {
    color: colorScheme.backgroundPrimary,
    fontWeight: '600',
    fontSize: 18,
  },
  // Review mode styles
  reviewScrollContent: {
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
  },
  reviewShareButton: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: colorScheme.success,
    paddingHorizontal: 32,
    paddingVertical: 12,
    borderRadius: 25,
    marginTop: 16,
  },
  reviewShareButtonText: {
    color: colorScheme.success,
    fontWeight: '600',
    fontSize: 16,
  },
  reviewHeaderTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colorScheme.textPrimary,
  },
  headerPlaceholder: {
    width: 44,
  },
  reviewPercentileRow: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: colorScheme.borderPrimary,
    alignItems: 'center',
  },
  reviewPercentileText: {
    fontSize: 18,
    color: colorScheme.warning,
    fontWeight: '600',
  },
  reviewSubtitle: {
    fontSize: 16,
    color: colorScheme.textTertiary,
    marginTop: 24,
    marginBottom: 12,
  },
  reviewGridContainer: {
    alignItems: 'center',
  },
  // Grid container
  gridContainer: {
    alignItems: 'center',
    paddingTop: 8,
  },
  // Game complete result screen styles (embedded leaderboard)
  gameCompleteScrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 40,
    paddingBottom: 40,
  },
  gameCompleteHeader: {
    alignItems: 'center',
    marginBottom: 24,
  },
  gameCompleteTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  gameCompleteRankText: {
    fontSize: 18,
    color: colorScheme.gold,
    fontWeight: '600',
    marginTop: 8,
  },
  gameCompleteScoreCard: {
    backgroundColor: colorScheme.backgroundSecondary,
    borderRadius: 12,
    padding: 16,
    width: '100%',
    maxWidth: 400,
    marginBottom: 16,
  },
  gameCompleteScoreRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  gameCompleteScoreItem: {
    alignItems: 'center',
  },
  gameCompleteScoreValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colorScheme.textPrimary,
  },
  gameCompleteScoreLabel: {
    fontSize: 12,
    color: colorScheme.textTertiary,
    marginTop: 4,
  },
  gameCompleteLeaderboardCard: {
    backgroundColor: colorScheme.backgroundSecondary,
    borderRadius: 12,
    padding: 16,
    width: '100%',
    maxWidth: 400,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colorScheme.borderPrimary,
  },
  gameCompleteLeaderboardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  gameCompleteLeaderboardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  gameCompleteLeaderboardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colorScheme.textPrimary,
  },
  gameCompleteActions: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
    width: '100%',
    maxWidth: 400,
  },
  gameCompleteActionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colorScheme.backgroundSecondary,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colorScheme.borderPrimary,
  },
  gameCompleteActionButtonText: {
    color: colorScheme.brandPrimary,
    fontWeight: '600',
    fontSize: 14,
  },
  gameCompleteShareButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colorScheme.success,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
  },
  gameCompleteShareButtonText: {
    color: colorScheme.warmBlack,
    fontWeight: '600',
    fontSize: 14,
  },
  gameCompleteSignInButton: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colorScheme.gold,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
  },
  gameCompleteSignInButtonText: {
    color: colorScheme.warmBlack,
    fontWeight: '700',
    fontSize: 15,
  },
  gameCompleteBackButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
  },
  gameCompleteBackButtonText: {
    color: colorScheme.textTertiary,
    fontSize: 14,
  },
  homeLeaderboardTabBar: {
    flexDirection: 'row',
    marginTop: 8,
    width: '80%',
    backgroundColor: colorScheme.backgroundTertiary,
    borderRadius: 6,
    padding: 2,
  },
  homeLeaderboardTab: {
    flex: 1,
    paddingVertical: 3,
    alignItems: 'center',
    borderRadius: 4,
  },
  homeLeaderboardTabActive: {
    backgroundColor: colorScheme.brandPrimary,
  },
  homeLeaderboardTabText: {
    fontSize: 13,
    fontWeight: '500',
    color: colorScheme.textTertiary,
  },
  homeLeaderboardTabTextActive: {
    color: colorScheme.textPrimary,
    fontWeight: '600',
  },
});

