-- Generated from LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words (en).
create table if not exists public.bad_words (
  word text primary key,
  word_normalized text not null
);

insert into public.bad_words (word, word_normalized) values
  ('2g1c', '2g1c'),
  ('2 girls 1 cup', '2girls1cup'),
  ('acrotomophilia', 'acrotomophilia'),
  ('alabama hot pocket', 'alabamahotpocket'),
  ('alaskan pipeline', 'alaskanpipeline'),
  ('anal', 'anal'),
  ('anilingus', 'anilingus'),
  ('anus', 'anus'),
  ('apeshit', 'apeshit'),
  ('arsehole', 'arsehole'),
  ('ass', 'ass'),
  ('asshole', 'asshole'),
  ('assmunch', 'assmunch'),
  ('auto erotic', 'autoerotic'),
  ('babeland', 'babeland'),
  ('baby batter', 'babybatter'),
  ('baby juice', 'babyjuice'),
  ('ball gag', 'ballgag'),
  ('ball gravy', 'ballgravy'),
  ('ball kicking', 'ballkicking'),
  ('ball licking', 'balllicking'),
  ('ball sack', 'ballsack'),
  ('ball sucking', 'ballsucking'),
  ('bangbros', 'bangbros'),
  ('bangbus', 'bangbus'),
  ('bareback', 'bareback'),
  ('barely legal', 'barelylegal'),
  ('barenaked', 'barenaked'),
  ('bastard', 'bastard'),
  ('bastardo', 'bastardo'),
  ('bastinado', 'bastinado'),
  ('bbw', 'bbw'),
  ('bdsm', 'bdsm'),
  ('beaner', 'beaner'),
  ('beaners', 'beaners'),
  ('beaver cleaver', 'beavercleaver'),
  ('beaver lips', 'beaverlips'),
  ('beastiality', 'beastiality'),
  ('bestiality', 'bestiality'),
  ('big black', 'bigblack'),
  ('big breasts', 'bigbreasts'),
  ('big knockers', 'bigknockers'),
  ('big tits', 'bigtits'),
  ('bimbos', 'bimbos'),
  ('birdlock', 'birdlock'),
  ('bitch', 'bitch'),
  ('bitches', 'bitches'),
  ('black cock', 'blackcock'),
  ('blonde action', 'blondeaction'),
  ('blonde on blonde action', 'blondeonblondeaction'),
  ('blowjob', 'blowjob'),
  ('blow your load', 'blowyourload'),
  ('blue waffle', 'bluewaffle'),
  ('blumpkin', 'blumpkin'),
  ('bollocks', 'bollocks'),
  ('bondage', 'bondage'),
  ('boner', 'boner'),
  ('boob', 'boob'),
  ('boobs', 'boobs'),
  ('booty call', 'bootycall'),
  ('brown showers', 'brownshowers'),
  ('brunette action', 'brunetteaction'),
  ('bukkake', 'bukkake'),
  ('bulldyke', 'bulldyke'),
  ('bullet vibe', 'bulletvibe'),
  ('bullshit', 'bullshit'),
  ('bung hole', 'bunghole'),
  ('busty', 'busty'),
  ('butt', 'butt'),
  ('buttcheeks', 'buttcheeks'),
  ('butthole', 'butthole'),
  ('camel toe', 'cameltoe'),
  ('camgirl', 'camgirl'),
  ('camslut', 'camslut'),
  ('camwhore', 'camwhore'),
  ('carpet muncher', 'carpetmuncher'),
  ('chocolate rosebuds', 'chocolaterosebuds'),
  ('cialis', 'cialis'),
  ('circlejerk', 'circlejerk'),
  ('cleveland steamer', 'clevelandsteamer'),
  ('clit', 'clit'),
  ('clitoris', 'clitoris'),
  ('clover clamps', 'cloverclamps'),
  ('clusterfuck', 'clusterfuck'),
  ('cock', 'cock'),
  ('cocks', 'cocks'),
  ('coprolagnia', 'coprolagnia'),
  ('coprophilia', 'coprophilia'),
  ('cornhole', 'cornhole'),
  ('coon', 'coon'),
  ('coons', 'coons'),
  ('creampie', 'creampie'),
  ('cum', 'cum'),
  ('cumming', 'cumming'),
  ('cumshot', 'cumshot'),
  ('cumshots', 'cumshots'),
  ('cunnilingus', 'cunnilingus'),
  ('cunt', 'cunt'),
  ('darkie', 'darkie'),
  ('date rape', 'daterape'),
  ('deep throat', 'deepthroat'),
  ('dendrophilia', 'dendrophilia'),
  ('dick', 'dick'),
  ('dildo', 'dildo'),
  ('dingleberry', 'dingleberry'),
  ('dingleberries', 'dingleberries'),
  ('dirty pillows', 'dirtypillows'),
  ('dirty sanchez', 'dirtysanchez'),
  ('doggie style', 'doggiestyle'),
  ('doggy style', 'doggystyle'),
  ('dog style', 'dogstyle'),
  ('dolcett', 'dolcett'),
  ('domination', 'domination'),
  ('dominatrix', 'dominatrix'),
  ('dommes', 'dommes'),
  ('donkey punch', 'donkeypunch'),
  ('double dong', 'doubledong'),
  ('double penetration', 'doublepenetration'),
  ('dp action', 'dpaction'),
  ('dry hump', 'dryhump'),
  ('dvda', 'dvda'),
  ('eat my ass', 'eatmyass'),
  ('ecchi', 'ecchi'),
  ('ejaculation', 'ejaculation'),
  ('erotic', 'erotic'),
  ('erotism', 'erotism'),
  ('escort', 'escort'),
  ('eunuch', 'eunuch'),
  ('fag', 'fag'),
  ('faggot', 'faggot'),
  ('fecal', 'fecal'),
  ('felch', 'felch'),
  ('fellatio', 'fellatio'),
  ('feltch', 'feltch'),
  ('female squirting', 'femalesquirting'),
  ('femdom', 'femdom'),
  ('figging', 'figging'),
  ('fingerbang', 'fingerbang'),
  ('fingering', 'fingering'),
  ('fisting', 'fisting'),
  ('foot fetish', 'footfetish'),
  ('footjob', 'footjob'),
  ('frotting', 'frotting'),
  ('fuck', 'fuck'),
  ('fuck buttons', 'fuckbuttons'),
  ('fuckin', 'fuckin'),
  ('fucking', 'fucking'),
  ('fucktards', 'fucktards'),
  ('fudge packer', 'fudgepacker'),
  ('futanari', 'futanari'),
  ('gangbang', 'gangbang'),
  ('gay sex', 'gaysex'),
  ('genitals', 'genitals'),
  ('giant cock', 'giantcock'),
  ('girl on', 'girlon'),
  ('girl on top', 'girlontop'),
  ('girls gone wild', 'girlsgonewild'),
  ('goatcx', 'goatcx'),
  ('goatse', 'goatse'),
  ('god damn', 'goddamn'),
  ('gokkun', 'gokkun'),
  ('golden shower', 'goldenshower'),
  ('goodpoop', 'goodpoop'),
  ('goo girl', 'googirl'),
  ('goregasm', 'goregasm'),
  ('grope', 'grope'),
  ('group sex', 'groupsex'),
  ('g-spot', 'gspot'),
  ('guro', 'guro'),
  ('hand job', 'handjob'),
  ('hard core', 'hardcore'),
  ('hentai', 'hentai'),
  ('homoerotic', 'homoerotic'),
  ('honkey', 'honkey'),
  ('hooker', 'hooker'),
  ('horny', 'horny'),
  ('hot carl', 'hotcarl'),
  ('hot chick', 'hotchick'),
  ('how to kill', 'howtokill'),
  ('how to murder', 'howtomurder'),
  ('huge fat', 'hugefat'),
  ('humping', 'humping'),
  ('incest', 'incest'),
  ('intercourse', 'intercourse'),
  ('jack off', 'jackoff'),
  ('jail bait', 'jailbait'),
  ('jelly donut', 'jellydonut'),
  ('jerk off', 'jerkoff'),
  ('jigaboo', 'jigaboo'),
  ('jiggaboo', 'jiggaboo'),
  ('jiggerboo', 'jiggerboo'),
  ('jizz', 'jizz'),
  ('juggs', 'juggs'),
  ('kike', 'kike'),
  ('kinbaku', 'kinbaku'),
  ('kinkster', 'kinkster'),
  ('kinky', 'kinky'),
  ('knobbing', 'knobbing'),
  ('leather restraint', 'leatherrestraint'),
  ('leather straight jacket', 'leatherstraightjacket'),
  ('lemon party', 'lemonparty'),
  ('livesex', 'livesex'),
  ('lolita', 'lolita'),
  ('lovemaking', 'lovemaking'),
  ('make me come', 'makemecome'),
  ('male squirting', 'malesquirting'),
  ('masturbate', 'masturbate'),
  ('masturbating', 'masturbating'),
  ('masturbation', 'masturbation'),
  ('menage a trois', 'menageatrois'),
  ('milf', 'milf'),
  ('missionary position', 'missionaryposition'),
  ('mong', 'mong'),
  ('motherfucker', 'motherfucker'),
  ('mound of venus', 'moundofvenus'),
  ('mr hands', 'mrhands'),
  ('muff diver', 'muffdiver'),
  ('muffdiving', 'muffdiving'),
  ('nambla', 'nambla'),
  ('nawashi', 'nawashi'),
  ('negro', 'negro'),
  ('neonazi', 'neonazi'),
  ('nigga', 'nigga'),
  ('nigger', 'nigger'),
  ('nig nog', 'nignog'),
  ('nimphomania', 'nimphomania'),
  ('nipple', 'nipple'),
  ('nipples', 'nipples'),
  ('nsfw', 'nsfw'),
  ('nsfw images', 'nsfwimages'),
  ('nude', 'nude'),
  ('nudity', 'nudity'),
  ('nutten', 'nutten'),
  ('nympho', 'nympho'),
  ('nymphomania', 'nymphomania'),
  ('octopussy', 'octopussy'),
  ('omorashi', 'omorashi'),
  ('one cup two girls', 'onecuptwogirls'),
  ('one guy one jar', 'oneguyonejar'),
  ('orgasm', 'orgasm'),
  ('orgy', 'orgy'),
  ('paedophile', 'paedophile'),
  ('paki', 'paki'),
  ('panties', 'panties'),
  ('panty', 'panty'),
  ('pedobear', 'pedobear'),
  ('pedophile', 'pedophile'),
  ('pegging', 'pegging'),
  ('penis', 'penis'),
  ('phone sex', 'phonesex'),
  ('piece of shit', 'pieceofshit'),
  ('pikey', 'pikey'),
  ('pissing', 'pissing'),
  ('piss pig', 'pisspig'),
  ('playboy', 'playboy'),
  ('pleasure chest', 'pleasurechest'),
  ('pole smoker', 'polesmoker'),
  ('ponyplay', 'ponyplay'),
  ('poof', 'poof'),
  ('poon', 'poon'),
  ('poontang', 'poontang'),
  ('punany', 'punany'),
  ('poop chute', 'poopchute'),
  ('porn', 'porn'),
  ('porno', 'porno'),
  ('pornography', 'pornography'),
  ('prince albert piercing', 'princealbertpiercing'),
  ('pthc', 'pthc'),
  ('pubes', 'pubes'),
  ('pussy', 'pussy'),
  ('queaf', 'queaf'),
  ('queef', 'queef'),
  ('quim', 'quim'),
  ('raghead', 'raghead'),
  ('raging boner', 'ragingboner'),
  ('rape', 'rape'),
  ('raping', 'raping'),
  ('rapist', 'rapist'),
  ('rectum', 'rectum'),
  ('reverse cowgirl', 'reversecowgirl'),
  ('rimjob', 'rimjob'),
  ('rimming', 'rimming'),
  ('rosy palm', 'rosypalm'),
  ('rosy palm and her 5 sisters', 'rosypalmandher5sisters'),
  ('rusty trombone', 'rustytrombone'),
  ('sadism', 'sadism'),
  ('santorum', 'santorum'),
  ('scat', 'scat'),
  ('schlong', 'schlong'),
  ('scissoring', 'scissoring'),
  ('semen', 'semen'),
  ('sex', 'sex'),
  ('sexcam', 'sexcam'),
  ('sexo', 'sexo'),
  ('sexy', 'sexy'),
  ('sexual', 'sexual'),
  ('sexually', 'sexually'),
  ('sexuality', 'sexuality'),
  ('shaved beaver', 'shavedbeaver'),
  ('shaved pussy', 'shavedpussy'),
  ('shemale', 'shemale'),
  ('shibari', 'shibari'),
  ('shit', 'shit'),
  ('shitblimp', 'shitblimp'),
  ('shitty', 'shitty'),
  ('shota', 'shota'),
  ('shrimping', 'shrimping'),
  ('skeet', 'skeet'),
  ('slanteye', 'slanteye'),
  ('slut', 'slut'),
  ('smut', 'smut'),
  ('snatch', 'snatch'),
  ('snowballing', 'snowballing'),
  ('sodomize', 'sodomize'),
  ('sodomy', 'sodomy'),
  ('spastic', 'spastic'),
  ('spic', 'spic'),
  ('splooge', 'splooge'),
  ('splooge moose', 'sploogemoose'),
  ('spooge', 'spooge'),
  ('spread legs', 'spreadlegs'),
  ('spunk', 'spunk'),
  ('strap on', 'strapon'),
  ('strappado', 'strappado'),
  ('strip club', 'stripclub'),
  ('style doggy', 'styledoggy'),
  ('suck', 'suck'),
  ('sucks', 'sucks'),
  ('suicide girls', 'suicidegirls'),
  ('sultry women', 'sultrywomen'),
  ('swastika', 'swastika'),
  ('swinger', 'swinger'),
  ('tainted love', 'taintedlove'),
  ('taste my', 'tastemy'),
  ('tea bagging', 'teabagging'),
  ('threesome', 'threesome'),
  ('throating', 'throating'),
  ('thumbzilla', 'thumbzilla'),
  ('tied up', 'tiedup'),
  ('tight white', 'tightwhite'),
  ('tit', 'tit'),
  ('tits', 'tits'),
  ('titties', 'titties'),
  ('titty', 'titty'),
  ('tongue in a', 'tongueina'),
  ('topless', 'topless'),
  ('tosser', 'tosser'),
  ('towelhead', 'towelhead'),
  ('tranny', 'tranny'),
  ('tribadism', 'tribadism'),
  ('tub girl', 'tubgirl'),
  ('tushy', 'tushy'),
  ('twat', 'twat'),
  ('twink', 'twink'),
  ('twinkie', 'twinkie'),
  ('two girls one cup', 'twogirlsonecup'),
  ('undressing', 'undressing'),
  ('upskirt', 'upskirt'),
  ('urethra play', 'urethraplay'),
  ('urophilia', 'urophilia'),
  ('vagina', 'vagina'),
  ('venus mound', 'venusmound'),
  ('viagra', 'viagra'),
  ('vibrator', 'vibrator'),
  ('violet wand', 'violetwand'),
  ('vorarephilia', 'vorarephilia'),
  ('voyeur', 'voyeur'),
  ('voyeurweb', 'voyeurweb'),
  ('voyuer', 'voyuer'),
  ('vulva', 'vulva'),
  ('wank', 'wank'),
  ('wetback', 'wetback'),
  ('wet dream', 'wetdream'),
  ('white power', 'whitepower'),
  ('whore', 'whore'),
  ('worldsex', 'worldsex'),
  ('wrapping men', 'wrappingmen'),
  ('wrinkled starfish', 'wrinkledstarfish'),
  ('xxx', 'xxx'),
  ('yaoi', 'yaoi'),
  ('yellow showers', 'yellowshowers'),
  ('yiffy', 'yiffy'),
  ('zoophilia', 'zoophilia')
on conflict (word) do nothing;

create or replace function public.enforce_display_name()
returns trigger as $$
declare
  cleaned text;
begin
  if new.display_name is null then
    return new;
  end if;

  if new.display_name !~ '^[A-Za-z0-9 _.-]{3,20}$' then
    raise exception 'invalid display name';
  end if;

  cleaned := lower(translate(new.display_name, '013457@$!', 'oieastasi'));
  cleaned := regexp_replace(cleaned, '[^a-z0-9]', '', 'g');

  if exists (
    select 1 from public.bad_words
    where cleaned like '%' || word_normalized || '%'
  ) then
    raise exception 'invalid display name';
  end if;

  return new;
end;
$$ language plpgsql;

drop trigger if exists profiles_display_name_enforce on public.profiles;
create trigger profiles_display_name_enforce
before insert or update of display_name on public.profiles
for each row
execute function public.enforce_display_name();
